bielik-1-5b-v3-instruct:
  name: "bielik-1-5b-v3-instruct"
  path: "speakleash/Bielik-1.5B-v3-Instruct"
  family: "bielik"
  generation_params:
    max_new_tokens: 1024
    temperature: 0.6
    do_sample: true
    top_p: 0.95

bielik-4-5b-v3-instruct:
  name: "bielik-4-5b-v3-instruct"
  path: "speakleash/Bielik-4.5B-v3-Instruct"
  family: "bielik"
  inference_backend: "vllm"
  generation_params:
    max_new_tokens: 1536
    temperature: 0.6
    do_sample: true
    top_p: 0.95

bielik-11b-v26-instruct-fp8-dynamic:
  name: "bielik-11b-v26-instruct-fp8-dynamic"
  path: "speakleash/Bielik-11B-v2.6-Instruct"
  family: "bielik"
  inference_backend: "vllm"
  quantization: "fp8-dynamic"
  generation_params:
    max_new_tokens: 1536
    temperature: 0.6
    do_sample: true
    top_p: 0.95

qwen3-1-7b:
  name: "qwen3-1-7b"
  path: "Qwen/Qwen3-1.7B"
  family: "qwen3"
  generation_params:
    max_new_tokens: 1024
    temperature: 0.6
    do_sample: true
    top_p: 0.95
  prompt_template_params:
    enable_thinking: true

qwen3-4b:
  name: "qwen3-4b"
  path: "Qwen/Qwen3-4B"
  family: "qwen3"
  inference_backend: "vllm"
  generation_params:
    max_new_tokens: 1536
    temperature: 0.6
    do_sample: true
    top_p: 0.95
  prompt_template_params:
    enable_thinking: true

qwen3-14b-fp8:
  name: "qwen3-14b-fp8"
  path: "Qwen/Qwen3-14B-FP8"
  family: "qwen3"
  inference_backend: "vllm"
  quantization: "fp8"
  generation_params:
    max_new_tokens: 1536
    temperature: 0.6
    do_sample: true
    top_p: 0.95
  prompt_template_params:
    enable_thinking: true

pllum-8b-instruct:
  name: "pllum-8b-instruct"
  path: "CYFRAGOVPL/Llama-PLLuM-8B-instruct"
  family: "pllum"
  inference_backend: "vllm"
  generation_params:
    max_new_tokens: 1536
    temperature: 0.6
    do_sample: true
    top_p: 0.95

pllum-12b-instruct:
  name: "pllum-12b-instruct"
  path: "CYFRAGOVPL/PLLuM-12B-instruct"
  family: "pllum"
  inference_backend: "vllm"
  quantization: "fp8"
  generation_params:
    max_new_tokens: 1536
    temperature: 0.6
    do_sample: true
    top_p: 0.95