experiments:
  bielik-precise-matura:
    task_name: "Bielik 1.5B v3 - Odpowiedzi precyzyjne na pytania maturalne"
    model: bielik-1-5b-v3-instruct
    input_dataset: "data/dataset/mvp_dataset_2025-06-08T20-42-43Z.json"
    output_dir: "results/bielik_precise"
    param_overrides:
      per_type:
        closed_MTF:
          do_sample: false
          temperature: 0.01

  qwen-thinking-matura:
    task_name: "Qwen3 1.7B - Odpowiedzi z myśleniem 'krok po kroku'"
    model: qwen3-1-7b
    input_dataset: "data/dataset/mvp_dataset_2025-06-08T20-42-43Z.json"
    output_dir: "results/qwen_thinking"
    param_overrides:
      default:
        enable_thinking: true
