experiments:
  bielik-small-simple-matura:
    task_name: "Bielik 1.5B - Prosty (Zero-Shot) - zbiór maturalny"
    model: bielik-1-5b-v3-instruct
    input_dataset: "data/dataset/polski_matura_dataset_2025-06-23T13-08-12Z.json"
    output_dir: "results/bielik-small-simple-matura"
    iterations: 1
    prompt_composition:
      components: []
    param_overrides: {}

  bielik-small-full-matura:
    task_name: "Bielik 1.5B - Pełny (Few-Shot + CoT) - zbiór maturalny"
    model: bielik-1-5b-v3-instruct
    input_dataset: "data/dataset/polski_matura_dataset_2025-06-23T13-08-12Z.json"
    output_dir: "results/bielik-small-full-matura"
    iterations: 1
    prompt_composition:
      components: ["few_shot", "chain_of_thought"]
    param_overrides:
      per_type:
        open_essay: { max_new_tokens: 2048 }
        open_poetry_interpretation: { max_new_tokens: 2048 }

  bielik-medium-simple-matura:
    task_name: "Bielik 4.5B - Prosty (Zero-Shot) - zbiór maturalny"
    model: bielik-4-5b-v3-instruct
    input_dataset: "data/dataset/polski_matura_dataset_2025-06-23T13-08-12Z.json"
    output_dir: "results/bielik-medium-simple-matura"
    iterations: 1
    prompt_composition:
      components: []
    param_overrides:
      per_type:
        open_essay: { max_new_tokens: 2048 }
        open_poetry_interpretation: { max_new_tokens: 2048 }

  bielik-medium-full-matura:
    task_name: "Bielik 4.5B - Pełny (Few-Shot + CoT) - zbiór maturalny"
    model: bielik-4-5b-v3-instruct
    input_dataset: "data/dataset/polski_matura_dataset_2025-06-23T13-08-12Z.json"
    output_dir: "results/bielik-medium-full-matura"
    iterations: 1
    prompt_composition:
      components: ["few_shot", "chain_of_thought"]
      template_params: { num_few_shot: 2 }
    param_overrides:
      per_type:
        open_essay: { max_new_tokens: 3072 }
        open_poetry_interpretation: { max_new_tokens: 3072 }
        open_summary: { max_new_tokens: 2048 }
        open_synthesis: { max_new_tokens: 2048 }
        open_text: { max_new_tokens: 1536 }

  bielik-normal-fp8-simple-matura:
    task_name: "Bielik 11B FP8 - Prosty (Zero-Shot) - zbiór maturalny"
    model: bielik-11b-v26-instruct-fp8-dynamic
    input_dataset: "data/dataset/polski_matura_dataset_2025-06-23T13-08-12Z.json"
    output_dir: "results/bielik-normal-fp8-simple-matura"
    iterations: 1
    prompt_composition:
      components: []
    param_overrides:
      per_type:
        open_essay: { max_new_tokens: 2048 }
        open_poetry_interpretation: { max_new_tokens: 2048 }

  bielik-normal-fp8-full-matura:
    task_name: "Bielik 11B FP8 - Pełny (Few-Shot + CoT) - zbiór maturalny"
    model: bielik-11b-v26-instruct-fp8-dynamic
    input_dataset: "data/dataset/polski_matura_dataset_2025-06-23T13-08-12Z.json"
    output_dir: "results/bielik-normal-fp8-full-matura"
    iterations: 1
    prompt_composition:
      components: ["few_shot", "chain_of_thought"]
      template_params: { num_few_shot: 2 }
    param_overrides:
      per_type:
        open_essay: { max_new_tokens: 3072 }
        open_poetry_interpretation: { max_new_tokens: 3072 }
        open_summary: { max_new_tokens: 2048 }
        open_synthesis: { max_new_tokens: 2048 }
        open_text: { max_new_tokens: 1536 }

  pllum-medium-simple-matura:
    task_name: "PLLuM 8B - Prosty (Zero-Shot) - zbiór maturalny"
    model: pllum-8b-instruct
    input_dataset: "data/dataset/polski_matura_dataset_2025-06-23T13-08-12Z.json"
    output_dir: "results/pllum-medium-simple-matura"
    iterations: 1
    prompt_composition:
      components: []
    param_overrides:
      per_type:
        open_essay: { max_new_tokens: 2048 }
        open_poetry_interpretation: { max_new_tokens: 2048 }

  pllum-medium-full-matura:
    task_name: "PLLuM 8B - Pełny (Few-Shot + CoT) - zbiór maturalny"
    model: pllum-8b-instruct
    input_dataset: "data/dataset/polski_matura_dataset_2025-06-23T13-08-12Z.json"
    output_dir: "results/pllum-medium-full-matura"
    iterations: 1
    prompt_composition:
      components: ["few_shot", "chain_of_thought"]
      template_params: { num_few_shot: 2 }
    param_overrides:
      per_type:
        open_essay: { max_new_tokens: 3072 }
        open_poetry_interpretation: { max_new_tokens: 3072 }
        open_summary: { max_new_tokens: 2048 }
        open_synthesis: { max_new_tokens: 2048 }
        open_text: { max_new_tokens: 1536 }

  pllum-normal-fp8-simple-matura:
    task_name: "PLLuM 12B FP8 - Prosty (Zero-Shot) - zbiór maturalny"
    model: pllum-12b-instruct-fp8
    input_dataset: "data/dataset/polski_matura_dataset_2025-06-23T13-08-12Z.json"
    output_dir: "results/pllum-normal-fp8-simple-matura"
    iterations: 1
    prompt_composition:
      components: []
    param_overrides:
      per_type:
        open_essay: { max_new_tokens: 2048 }
        open_poetry_interpretation: { max_new_tokens: 2048 }

  pllum-normal-fp8-full-matura:
    task_name: "PLLuM 12B FP8 - Pełny (Few-Shot + CoT) - zbiór maturalny"
    model: pllum-12b-instruct-fp8
    input_dataset: "data/dataset/polski_matura_dataset_2025-06-23T13-08-12Z.json"
    output_dir: "results/pllum-normal-fp8-full-matura"
    iterations: 1
    prompt_composition:
      components: ["few_shot", "chain_of_thought"]
      template_params: { num_few_shot: 2 }
    param_overrides:
      per_type:
        open_essay: { max_new_tokens: 3072 }
        open_poetry_interpretation: { max_new_tokens: 3072 }
        open_summary: { max_new_tokens: 2048 }
        open_synthesis: { max_new_tokens: 2048 }
        open_text: { max_new_tokens: 1536 }

  qwen-small-simple-matura:
    task_name: "Qwen3 1.7B - Prosty (Zero-Shot, No-Thinking) - zbiór maturalny"
    model: qwen3-1-7b
    input_dataset: "data/dataset/polski_matura_dataset_2025-06-23T13-08-12Z.json"
    output_dir: "results/qwen-small-simple-matura"
    iterations: 1
    prompt_composition:
      main_template: "base_question_prompt.jinja2"
      components: []
    param_overrides:
      default:
        enable_thinking: false
      per_type:
        open_essay:
          max_new_tokens: 2048
        open_poetry_interpretation:
          max_new_tokens: 2048

  qwen-small-full-matura:
    task_name: "Qwen3 1.7B - Pełny (Few-Shot + CoT + Thinking) - zbiór maturalny"
    model: qwen3-1-7b
    input_dataset: "data/dataset/polski_matura_dataset_2025-06-23T13-08-12Z.json"
    output_dir: "results/qwen-small-full-matura"
    iterations: 1
    prompt_composition:
      main_template: "base_question_prompt.jinja2"
      components: ["few_shot", "chain_of_thought"]
      template_params:
        show_thinking_output: true
    param_overrides:
      default:
        enable_thinking: true
      per_type:
        open_essay: { max_new_tokens: 3072 }
        open_poetry_interpretation: { max_new_tokens: 3072 }
        open_summary: { max_new_tokens: 2048 }
        open_synthesis: { max_new_tokens: 2048 }
        open_text: { max_new_tokens: 1536 }

  qwen-medium-simple-matura:
    task_name: "Qwen3 4B - Prosty (Zero-Shot, No-Thinking) - zbiór maturalny"
    model: qwen3-4b
    input_dataset: "data/dataset/polski_matura_dataset_2025-06-23T13-08-12Z.json"
    output_dir: "results/qwen-4b-fp8-simple"
    iterations: 1
    prompt_composition:
      components: []
    param_overrides:
      default: { enable_thinking: false }
      per_type:
        open_essay: { max_new_tokens: 2048 }
        open_poetry_interpretation: { max_new_tokens: 2048 }

  qwen-medium-full-matura:
    task_name: "Qwen3 4B - Pełny (Few-Shot + CoT + Thinking) - zbiór maturalny"
    model: qwen3-4b
    input_dataset: "data/dataset/polski_matura_dataset_2025-06-23T13-08-12Z.json"
    output_dir: "results/qwen-medium-full-matura"
    iterations: 1
    prompt_composition:
      components: ["few_shot", "chain_of_thought"]
      template_params: { num_few_shot: 2 }
    param_overrides:
      default: { enable_thinking: true }
      per_type:
        open_essay: { max_new_tokens: 3072 }
        open_poetry_interpretation: { max_new_tokens: 3072 }
        open_summary: { max_new_tokens: 2048 }
        open_synthesis: { max_new_tokens: 2048 }
        open_text: { max_new_tokens: 1536 }

  qwen-normal-fp8-simple-matura:
    task_name: "Qwen3 14B FP8 - Prosty (Zero-Shot, No-Thinking) - zbiór maturalny"
    model: qwen3-14b-fp8
    input_dataset: "data/dataset/polski_matura_dataset_2025-06-23T13-08-12Z.json"
    output_dir: "results/qwen-normal-fp8-simple-matura"
    iterations: 1
    prompt_composition:
      components: []
    param_overrides:
      default: { enable_thinking: false }
      per_type:
        open_essay: { max_new_tokens: 2048 }
        open_poetry_interpretation: { max_new_tokens: 3072 }

  qwen-normal-fp8-full-matura:
    task_name: "Qwen3 14B FP8 - Pełny (Few-Shot + CoT + Thinking) - zbiór maturalny"
    model: qwen3-14b-fp8
    input_dataset: "data/dataset/polski_matura_dataset_2025-06-23T13-08-12Z.json"
    output_dir: "results/qwen-normal-fp8-full-matura"
    iterations: 1
    prompt_composition:
      components: ["few_shot", "chain_of_thought"]
      template_params: { num_few_shot: 2 }
    param_overrides:
      default: { enable_thinking: true }
      per_type:
        open_essay: { max_new_tokens: 3072 }
        open_poetry_interpretation: { max_new_tokens: 3072 }
        open_summary: { max_new_tokens: 2048 }
        open_synthesis: { max_new_tokens: 2048 }
        open_text: { max_new_tokens: 1536 }
